#!/bin/bash

AUTOTOOLS_VERSION=libmesh
M4_VERSION=1.4.17
AUTOCONF_VERSION=2.69
AUTOMAKE_VERSION=1.15
LIBTOOL_VERSION=2.4.6

./build_autotools.sh $AUTOTOOLS_VERSION $M4_VERSION $AUTOCONF_VERSION $AUTOMAKE_VERSION $LIBTOOL_VERSION
